@echo off
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.1 > results_AP_0.1.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.2 > results_AP_0.2.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.3 > results_AP_0.3.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.4 > results_AP_0.4.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.5 > results_AP_0.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.6 > results_AP_0.6.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.7 > results_AP_0.7.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.8 > results_AP_0.8.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 0.9 > results_AP_0.9.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 1 > results_AP_1.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 1.2 > results_AP_1.2.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 1.5 > results_AP_1.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 1.7 > results_AP_1.7.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 2 > results_AP_2.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 2.5 > results_AP_2.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 3 > results_AP_3.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 3.5 > results_AP_3.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 4 > results_AP_4.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 4.5 > results_AP_4.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 5 > results_AP_5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 5.5 > results_AP_5.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 6 > results_AP_6.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 6.5 > results_AP_6.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 7 > results_AP_7.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 7.5 > results_AP_7.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 8 > results_AP_8.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 8.5 > results_AP_8.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 9 > results_AP_9.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 9.5 > results_AP_9.5.txt 2>&1
start /b "Python 3.11" "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\python.exe" auto_RESULTS-Multidigit_Addition_Decimal-Exponential_Decay.py 10 > results_AP_10.txt 2>&1
